import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { CartContextProvider } from "@/contexts/CartContext";

export const metadata: Metadata = {
  title: "My Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <CartContextProvider>
          <Layout>{children}</Layout>
        </CartContextProvider>
      </body>
    </html>
  );
}
